---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-a
spec:
  selector:
    matchLabels:
      app: hello
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
        version: v2
        tier: backend
        track: stable
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: hello-a
          image: "gcr.io/google-samples/hello-go-gke:1.0"
          ports:
            - name: http
              containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-b
spec:
  selector:
    matchLabels:
      app: hello
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
        version: v2
        tier: backend
        track: stable
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: hello-b
          image: "gcr.io/google-samples/hello-go-gke:1.0"
          ports:
            - name: http
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello
spec:
  selector:
    app: hello
    tier: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hello-vs
spec:
  hosts:
  - hello
  http:
  # route to subset based on header
  - match:
    - headers:
        custom-header:
          exact: a
      uri:
        prefix: "/ver1/"
      ignoreUriCase: true
    route:
    - destination:
        host: hello
        subset: v1
  # route to subset based on header
  - match:
    - headers:
        custom-header:
          exact: b
      uri:
        prefix: "/ver2/"
      ignoreUriCase: true
    route:
    - destination:
        host: hello
        subset: v2
  # # general routing
  - match:
    - uri:
        prefix: "/v1/"
    route:
    - destination:
        host: hello
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: hello-dr
spec:
  host: hello
  # trafficPolicy:
  #   loadBalancer:
  #     simple: RANDOM
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
---
